[package]
name = "web-app"
version = "0.9.0"
description = "The crypto-helper is an online app that helps to work with the diferent crypto algorithms."
edition = "2021"
authors = ["Pavlo Myroniuk <pspos.developqkation@gmail.com>"]
readme = "README.md"
license-file = "LICENSE"
repository = "https://github.com/TheBestTvarynka/crypto-helper"

[dependencies]
yew = { version = "0.20", features = ["csr"] }
yew-router = "0.17.0"
yew-notifications = { git = "https://github.com/TheBestTvarynka/yew-notifications.git", features = ["standard-notification"] }

# wasm
js-sys = "0.3.60"
wasm-bindgen = "0.2.83"
web-sys = { version = "0.3.60", features = ["Window"] }

# logging
wasm-logger = "0.2.0"
log = "0.4.17"

# utils
hex = "0.4.3"
gloo-timers = "0.2.4"
rand = { version = "0.8.5", default-features = false, features = ["small_rng"] }
rand_chacha = "0.3.1"
serde = { version = "1.0.162", features = ["derive"] }
serde_qs = "0.12.0"
serde_json = "1.0.89"
base64 = "0.13.1"
time = { version = "0.3.20", features = ["local-offset", "wasm-bindgen"] }

# crypto
picky-krb = { git = "https://github.com/TheBestTravynka/picky-rs.git", rev = "604a246" }
picky = { version = "7.0.0-rc.3", default-features = false, features = ["ec"] }
md5 = "0.7.0"
sha1 = "0.10.5"
hmac-sha256 = "1.1.5"
hmac-sha512 = { version = "1.1.2", features = ["sha384"] }
rsa = "0.7.2"
yew-hooks = "0.2.0"
